### ISSUE TITLE
Re: Interested in putting this up on Addon Manager?

### ISSUE THREAD

**Issue by Xanaxiel** [torahamu/TOSAddon#1]
Hey man! Nice addons, I've already thought of your `showmarketlevel` even before card/gem levels were a feature, made a prototype for headgears but haven't had the time to work on it. Are you interested in putting your addons up on [Addon Manager](https://github.com/Excrulon/Tree-of-Savior-Addon-Manager)?

**Comment by torahamu** [comment]
ありがとう、是非ともアドオンマネージャーに置きたい。
次のことをすればいいですか？
* 自分のリポジトリへのaddons.jsonの作成
* [ここ](https://github.com/Tree-of-Savior-Addon-Community/Addons/blob/master/addons.json)へのコミット
* releaseの作成

----
Sorry for Google translation

Thank you, I'd definitely want to put it on an add - on manager.
Should I do the following?
* Create addons.json to my repository
* Commit to [here](https://github.com/Tree-of-Savior-Addon-Community/Addons/blob/master/addons.json)
* Create release

**Comment by Riunia** [comment]
うん、そうですよ。
<hr>

Yes, that's correct.

**Comment by torahamu** [comment]
ありがとう！  
Pull Requestをしたので、後は待つだけです。  

--

Sorry for Google translation.  
Thank you!  
I did a pull request, so I just wait.

**Comment by Xanaxiel** [comment]
Yeah, let's hope Excrulon goes online to merge that in 

    On Thursday, November 24, 2016 6:42 AM, torahamu <notifications@github.com> wrote:
 

 ありがとう！
Pull Requestをしたので、後は待つだけです。--Sorry for Google translation.
Thank you!
I did a pull request, so I just wait.—

**Comment by Xanaxiel** [comment]
Closing this as it got merged already
