### ISSUE TITLE
Hello. May I ask questions to you?

### ISSUE THREAD

**Issue by Shania301** [torahamu/TOSAddon#9]
Hello torahamu I would like to know how did you update your IPF addons? The IPF suite seems to be outdated and I can't update addons now.. Telling me any alternative for the IPF suite that can extract and rebuild an IPF would greatly help me! Thank you in advance!!

**Comment by torahamu** [comment]
Hi Shania301,
You should use IPFUnpacker. 
Please look at Addon-Tutorial for details.
https://github.com/Tree-of-Savior-Addon-Community/Addon-Tutorial/wiki

Good luck!
